BEGIN;CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;SELECT plan(12);
INSERT INTO auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)VALUES('e1000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','branch-publication@test.invalid','',now(),'{}','{}',now(),now());
SET LOCAL ROLE service_role;INSERT INTO private.work_orchestration_allowlist(user_id,enabled_by,reason)VALUES('e1000000-0000-0000-0000-000000000001','e1000000-0000-0000-0000-000000000001','branch publication proof');INSERT INTO public.ai_conversations(id,user_id,role,content)VALUES('e1000000-0000-0000-0000-0000000000c1','e1000000-0000-0000-0000-000000000001','user','publish authorized branch');RESET ROLE;
SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000001',true);
SELECT lives_ok($$SELECT public.create_work_proposal('e1000000-0000-0000-0000-0000000000c1','low','programming','{"schema_version":1}','{"schema_version":1,"data":{"summary":"branch","objective":"branch","included_scope":["branch"],"excluded_scope":[],"expected_effects":[],"risks":[]}}')$$,'item criado');
SELECT set_config('anima.item',(SELECT id::text FROM public.work_items WHERE source_message_id='e1000000-0000-0000-0000-0000000000c1'),true);
SET LOCAL ROLE service_role;UPDATE public.work_items SET state='completed' WHERE id=current_setting('anima.item')::uuid;
INSERT INTO public.work_events(id,work_item_id,event_type,author,proposal_version,payload)VALUES
('e1000000-0000-0000-0000-0000000000e1',current_setting('anima.item')::uuid,'result_submitted','executor',1,jsonb_build_object('schema_version',1,'data',jsonb_build_object('attempt_id','attempt-1','executor_signal',jsonb_build_object('worktreeHandoff',jsonb_build_object('workItemId',current_setting('anima.item'),'attemptId','attempt-1','approvedProposalVersion',1,'branch','anima-work/attempt-1','baseSha',repeat('a',40),'commitSha',repeat('b',40)))))),
('e1000000-0000-0000-0000-0000000000e2',current_setting('anima.item')::uuid,'result_accepted','user',1,'{"schema_version":1,"data":{"accepted_result_event_id":"e1000000-0000-0000-0000-0000000000e1"}}'),
('e1000000-0000-0000-0000-0000000000e3',current_setting('anima.item')::uuid,'integration_decided','user',1,'{"schema_version":1,"data":{"attempt_id":"attempt-1","accepted_result_event_id":"e1000000-0000-0000-0000-0000000000e1","decision":"authorize","decision_id":"auth-1"}}');RESET ROLE;
SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000001',true);
SELECT set_config('anima.receipt',jsonb_build_object('kind','branch_publication','receiptId','r1','idempotencyKey','integration-publication:auth-1:'||repeat('b',40)||':branch','providerId','git-branch-publication-v1','repositoryId','repo','remoteName','origin','remoteBranch','anima-work/attempt-1','commitSha',repeat('b',40),'baseBranch','main','verifiedBaseSha',repeat('a',40),'disposition','created')::text,true);
SELECT throws_ok($$SELECT public.record_branch_published(current_setting('anima.item')::uuid,1,'wrong',current_setting('anima.receipt')::jsonb)$$,'P0002','integration authorization not found','autorização exata exigida');
SELECT lives_ok($$SELECT public.record_branch_published(current_setting('anima.item')::uuid,1,'auth-1',current_setting('anima.receipt')::jsonb)$$,'receipt correto persiste');
SELECT is((SELECT count(*)::int FROM public.work_events WHERE work_item_id=current_setting('anima.item')::uuid AND event_type='branch_published'),1,'um evento persistido');
SELECT is((SELECT payload->'data'->'receipt'->>'remoteBranch' FROM public.work_events WHERE work_item_id=current_setting('anima.item')::uuid AND event_type='branch_published'),'anima-work/attempt-1','branch exata persistida');
SELECT is((SELECT payload->'data'->'receipt'->>'commitSha' FROM public.work_events WHERE work_item_id=current_setting('anima.item')::uuid AND event_type='branch_published'),repeat('b',40),'commit exato persistido');
SELECT lives_ok($$SELECT public.record_branch_published(current_setting('anima.item')::uuid,1,'auth-1',current_setting('anima.receipt')::jsonb)$$,'replay idempotente');
SELECT is((SELECT count(*)::int FROM public.work_events WHERE work_item_id=current_setting('anima.item')::uuid AND event_type='branch_published'),1,'replay não duplica');
SELECT throws_ok($$SELECT public.record_branch_published(current_setting('anima.item')::uuid,1,'auth-1',jsonb_set(current_setting('anima.receipt')::jsonb,'{commitSha}',to_jsonb(repeat('c',40))))$$,'55000','branch publication receipt mismatch','commit divergente recusado');
SELECT throws_ok($$SELECT public.record_branch_published(current_setting('anima.item')::uuid,1,'auth-1',jsonb_set(current_setting('anima.receipt')::jsonb,'{remoteBranch}',to_jsonb('main'::text)))$$,'55000','branch publication receipt mismatch','branch divergente recusada');
SELECT is((SELECT state::text FROM public.work_items WHERE id=current_setting('anima.item')::uuid),'completed','estado permanece completed');
SELECT is((SELECT count(*)::int FROM public.work_events WHERE work_item_id=current_setting('anima.item')::uuid AND event_type::text IN('review_request_created','integrated')),0,'não cria PR nem integrated');
SELECT * FROM finish();ROLLBACK;
