import { createHmac } from 'node:crypto';
import { WorkOrchestrationService, type WorkProposal } from '@anima/core';
import type { Database } from '@anima/types';
import { createClient } from '@supabase/supabase-js';
import { SupabaseWorkOrchestrationRepository } from '.';
jest.setTimeout(120_000);
const url=process.env.SUPABASE_URL, key=process.env.SUPABASE_PUBLISHABLE_KEY, secret=process.env.SUPABASE_JWT_SECRET;
const integration=url&&key&&secret?describe:describe.skip;
const encode=(value:object):string=>Buffer.from(JSON.stringify(value)).toString('base64url');
const token=(sub:string):string=>{const header=encode({alg:'HS256',typ:'JWT'}),payload=encode({sub,role:'authenticated',aud:'authenticated',exp:Math.floor(Date.now()/1000)+3600});return `${header}.${payload}.${createHmac('sha256',secret!).update(`${header}.${payload}`).digest('base64url')}`;};
const service=(user:string)=>new WorkOrchestrationService(new SupabaseWorkOrchestrationRepository(createClient<Database>(url!,key!,{global:{headers:{Authorization:`Bearer ${token(user)}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})));
const proposal=(summary:string):WorkProposal=>({schemaVersion:1,data:{summary,objective:'Validar F3',includedScope:['domínio'],excludedScope:['UI'],expectedEffects:['fluxo'],risks:['nenhum']}});
let createdItemId='';
integration('integração serviço → adapter → Supabase',()=>{
  test('percorre o fluxo suportado até conclusão e lê projeção/eventos',async()=>{const s=service('31000000-0000-0000-0000-000000000001');const created=await s.createProposal({sourceMessageId:'32000000-0000-0000-0000-000000000001',impactLevel:'low',capability:'planning',intent:{kind:'integration'},proposal:proposal('v1')});expect(created.ok).toBe(true);if(!created.ok)return;createdItemId=created.value.id;const revised=await s.reviseProposal({workItemId:created.value.id,expectedProposalVersion:1,intent:{kind:'integration'},proposal:proposal('v2')});expect(revised.ok&&revised.value.proposalVersion).toBe(2);const stale=await s.resolveApproval({workItemId:created.value.id,expectedProposalVersion:1,decision:{type:'approve'}});expect(!stale.ok&&stale.error.code).toBe('version_conflict');const approved=await s.resolveApproval({workItemId:created.value.id,expectedProposalVersion:2,decision:{type:'approve'}});expect(approved.ok&&approved.value.state).toBe('approved');const started=await s.startWork({workItemId:created.value.id,expectedProposalVersion:2});expect(started.ok&&started.value.state).toBe('in_progress');const submitted=await s.submitResult({workItemId:created.value.id,expectedProposalVersion:2,result:{summary:'feito',resultReferences:['local:test']}});expect(submitted.ok&&submitted.value.state).toBe('review');const accepted=await s.reviewResult({workItemId:created.value.id,expectedProposalVersion:2,decision:{type:'accept'}});expect(accepted.ok&&accepted.value.state).toBe('completed');const read=await s.getItem(created.value.id),events=await s.listEvents(created.value.id);expect(read.ok&&read.value.state).toBe('completed');expect(events.ok&&events.value.map(e=>e.type)).toEqual(['work_proposed','proposal_revised','work_approved','work_started','result_submitted','result_accepted']);});
  test('tipa allowlist, mensagem inadequada e isolamento',async()=>{const off=await service('31000000-0000-0000-0000-000000000003').createProposal({sourceMessageId:'32000000-0000-0000-0000-000000000003',impactLevel:'low',capability:'planning',intent:{},proposal:proposal('off')});expect(!off.ok&&off.error.code).toBe('orchestration_not_enabled');const bad=await service('31000000-0000-0000-0000-000000000001').createProposal({sourceMessageId:'32000000-0000-0000-0000-000000000004',impactLevel:'low',capability:'planning',intent:{},proposal:proposal('bad')});expect(!bad.ok&&bad.error.code).toBe('source_message_not_eligible');const foreign=await service('31000000-0000-0000-0000-000000000002').getItem(createdItemId);expect(!foreign.ok&&foreign.error.code).toBe('work_item_not_found');});
});
