import type { Database, Tables } from '@anima/types';
import type { SupabaseClient } from '@supabase/supabase-js';
import { mapSupabaseFailure, proposalFromDatabase, proposalToDatabase, SupabaseWorkOrchestrationRepository } from '.';
const row: Tables<'work_items'>={id:'i',user_id:'u',source_message_id:'m',state:'proposed',impact_level:'low',capability:'planning',original_request:'pedido',intent:{kind:'build'},proposal:{schema_version:1,data:{summary:'s',objective:'o',included_scope:[],excluded_scope:[],expected_effects:[],risks:[]}},proposal_version:1,created_at:'2026-07-14T00:00:00Z',updated_at:'2026-07-14T00:00:00Z'};
const proposal={schemaVersion:1 as const,data:{summary:'s',objective:'o',includedScope:[],excludedScope:[],expectedEffects:[],risks:[]}};
const clientWithRpc=(rpc:jest.Mock):SupabaseClient<Database>=>{const query={select:()=>query,eq:()=>query,maybeSingle:async()=>({data:row,error:null})};return{rpc,from:()=>query} as unknown as SupabaseClient<Database>;};
describe('adapter Supabase',()=>{
  test('converte envelope em ambas as direções',()=>expect(proposalFromDatabase(proposalToDatabase(proposal))).toEqual(proposal));
  test('chama create_work_proposal com argumentos exatos',async()=>{const rpc=jest.fn().mockResolvedValue({data:row,error:null});const repo=new SupabaseWorkOrchestrationRepository(clientWithRpc(rpc));const result=await repo.createProposal({sourceMessageId:'m',impactLevel:'low',capability:'planning',intent:{kind:'build'},proposal});expect(result.ok).toBe(true);expect(rpc).toHaveBeenCalledWith('create_work_proposal',expect.objectContaining({source_message_id:'m',impact_level:'low',capability:'planning'}));});
  test('converte decisão sem permitir estado ou evento',async()=>{const rpc=jest.fn().mockResolvedValue({data:row,error:null});const repo=new SupabaseWorkOrchestrationRepository(clientWithRpc(rpc));await repo.resolveApproval({workItemId:'i',expectedProposalVersion:1,decision:{type:'request_changes',requestedChanges:'ajuste'}});expect(rpc).toHaveBeenCalledWith('resolve_approval',{work_item_id:'i',expected_proposal_version:1,decision:'request_changes',decision_context:{requested_changes:'ajuste'}});});
  test('converte revisão sem permitir estado ou evento',async()=>{const rpc=jest.fn().mockResolvedValue({data:{...row,state:'completed'},error:null});const repo=new SupabaseWorkOrchestrationRepository(clientWithRpc(rpc));await repo.reviewResult({workItemId:'i',expectedProposalVersion:1,reviewedResultEventId:'e1',decision:{type:'accept'}});expect(rpc).toHaveBeenCalledWith('review_work_result_versioned',{work_item_id:'i',expected_proposal_version:1,reviewed_result_event_id:'e1',decision:'accept',decision_context:{}});});
  test('anexa somente referências de contexto',async()=>{const rpc=jest.fn().mockResolvedValue({data:{id:'c',work_item_id:'i',version:1,context_references:[{kind:'message',id:'m'}],created_at:'2026-07-15T00:00:00Z'},error:null});const repo=new SupabaseWorkOrchestrationRepository(clientWithRpc(rpc));const result=await repo.attachContext({workItemId:'i',expectedProposalVersion:1,references:[{kind:'message',id:'m'}]});expect(result.ok).toBe(true);expect(rpc).toHaveBeenCalledWith('attach_work_context',{work_item_id:'i',expected_proposal_version:1,context_references:[{kind:'message',id:'m'}]});});
  test('mapeia SQLSTATE sem vazar mensagem',()=>{const result=mapSupabaseFailure({code:'55000',message:'detalhe interno'},true);expect(result).toEqual({ok:false,error:{code:'version_conflict',message:'O item mudou desde a última leitura.',retryable:false}});});
  test('falha de transporte após mutação é ambígua',async()=>{const rpc=jest.fn().mockResolvedValue({data:null,error:{message:'fetch failed'}});const result=await new SupabaseWorkOrchestrationRepository(clientWithRpc(rpc)).startWork({workItemId:'i',expectedProposalVersion:1});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('ambiguous_outcome');expect(rpc).toHaveBeenCalledTimes(1);});
});
