import type { AttachWorkContextCommand, CreateWorkProposalCommand, RequestProposalRevisionCommand, ResolveApprovalInput, ReviewWorkResultCommand, ReviseWorkProposalCommand, StartWorkCommand, SubmitWorkResultCommand, WorkContextSnapshot, WorkEvent, WorkItem, WorkItemId, WorkOperationResult, WorkOrchestrationRepository } from '@anima/core';
import { approvalDecisionContext, failure, resultReviewDecisionContext } from '@anima/core';
import type { Database, Json, Tables } from '@anima/types';
import type { SupabaseClient } from '@supabase/supabase-js';
import { mapSupabaseFailure } from './errors';
import { mapWorkContext, mapWorkEvent, mapWorkItem, proposalToDatabase } from './mappers';
type MutationName='create_work_proposal'|'request_work_proposal_revision'|'revise_work_proposal'|'resolve_approval'|'review_work_result_versioned'|'start_work'|'submit_work_result';
interface ObservedVersion { workItemId:string; expectedProposalVersion:number }
export class SupabaseWorkOrchestrationRepository implements WorkOrchestrationRepository {
  constructor(private readonly client:SupabaseClient<Database>) {}
  createProposal(c:CreateWorkProposalCommand){return this.mutate('create_work_proposal',{source_message_id:c.sourceMessageId,impact_level:c.impactLevel,capability:c.capability,intent:c.intent as Json,proposal:proposalToDatabase(c.proposal)});}
  reviseProposal(c:ReviseWorkProposalCommand){return this.mutate('revise_work_proposal',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,intent:c.intent as Json,proposal:proposalToDatabase(c.proposal)},c);}
  requestProposalRevision(c:RequestProposalRevisionCommand){return this.mutate('request_work_proposal_revision',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,requested_changes:c.requestedChanges,intent:c.intent as Json,proposal:proposalToDatabase(c.proposal)},c);}
  resolveApproval(c:ResolveApprovalInput){return this.mutate('resolve_approval',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,decision:c.decision.type,decision_context:approvalDecisionContext(c.decision)},c);}
  startWork(c:StartWorkCommand){return this.mutate('start_work',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion},c);}
  submitResult(c:SubmitWorkResultCommand){return this.mutate('submit_work_result',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,result:{summary:c.result.summary,result_references:[...c.result.resultReferences],...(c.result.validations===undefined?{}:{validations:c.result.validations.map(validation=>({label:validation.label,outcome:validation.outcome}))}),...(c.result.limitations===undefined?{}:{limitations:[...c.result.limitations]})}},c);}
  reviewResult(c:ReviewWorkResultCommand){return this.mutate('review_work_result_versioned',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,reviewed_result_event_id:c.reviewedResultEventId,decision:c.decision.type,decision_context:resultReviewDecisionContext(c.decision)},c);}
  async attachContext(c:AttachWorkContextCommand):Promise<WorkOperationResult<WorkContextSnapshot>>{const{data,error}=await this.client.rpc('attach_work_context',{work_item_id:c.workItemId,expected_proposal_version:c.expectedProposalVersion,context_references:c.references.map(reference=>({kind:reference.kind,id:reference.id}))});if(error)return mapSupabaseFailure(error,true);if(!data)return failure('ambiguous_outcome','A operação não retornou confirmação. Reconcilie antes de repetir.');try{return{ok:true,value:mapWorkContext(data as unknown as Tables<'work_contexts'>)}}catch(cause){return failure('persistence_failure','Contexto persistido inválido.',false,cause)}}
  async getItem(id:WorkItemId):Promise<WorkOperationResult<WorkItem>>{const{data,error}=await this.client.from('work_items').select('*').eq('id',id).maybeSingle();if(error)return mapSupabaseFailure(error,false);if(!data)return failure('work_item_not_found','Item de trabalho não encontrado.');try{return{ok:true,value:mapWorkItem(data)}}catch(cause){return failure('persistence_failure','Resposta persistida inválida.',false,cause)}}
  async findItemsBySourceMessageId(sourceMessageId:string):Promise<WorkOperationResult<readonly WorkItem[]>>{const{data,error}=await this.client.from('work_items').select('*').eq('source_message_id',sourceMessageId).order('created_at',{ascending:true});if(error)return mapSupabaseFailure(error,false);try{return{ok:true,value:(data??[]).map(mapWorkItem)}}catch(cause){return failure('persistence_failure','Resposta persistida inválida.',false,cause)}}
  async listEvents(id:WorkItemId):Promise<WorkOperationResult<readonly WorkEvent[]>>{const{data,error}=await this.client.from('work_events').select('*').eq('work_item_id',id).order('seq',{ascending:true});if(error)return mapSupabaseFailure(error,false);try{return{ok:true,value:(data??[]).map(mapWorkEvent)}}catch(cause){return failure('persistence_failure','Resposta persistida inválida.',false,cause)}}
  async listContexts(id:WorkItemId):Promise<WorkOperationResult<readonly WorkContextSnapshot[]>>{const{data,error}=await this.client.from('work_contexts').select('*').eq('work_item_id',id).order('version',{ascending:true});if(error)return mapSupabaseFailure(error,false);try{return{ok:true,value:(data??[]).map(mapWorkContext)}}catch(cause){return failure('persistence_failure','Contexto persistido inválido.',false,cause)}}
  private async mutate<N extends MutationName>(name:N,args:Database['public']['Functions'][N]['Args'],observed?:ObservedVersion):Promise<WorkOperationResult<WorkItem>>{const{data,error}=await this.client.rpc(name,args);if(error){const mapped=mapSupabaseFailure<WorkItem>(error,true);if(!mapped.ok&&mapped.error.code==='ambiguous_outcome'&&observed){const current=await this.getItem(observed.workItemId);if(current.ok&&current.value.proposalVersion!==observed.expectedProposalVersion)return failure('version_conflict','O item mudou desde a última leitura.');}return mapped;}if(!data)return failure('ambiguous_outcome','A operação não retornou confirmação. Reconcilie antes de repetir.');try{return{ok:true,value:mapWorkItem(data as unknown as Tables<'work_items'>)}}catch(cause){return failure('persistence_failure','Resposta persistida inválida.',false,cause)}}
}
