import { BoundedWorkExecutor, FakeWorkExecutor, type WorkExecutionRequest, type WorkExecutorAdapter } from '.';
const request:WorkExecutionRequest={workItemId:'w',capability:'programming',objective:'Validar contrato',contextReferences:[{kind:'message',id:'m'}],limits:{maxAttempts:2,timeoutMs:50,shutdownGraceMs:20}};
describe('fronteira limitada de executores',()=>{
  test('retorna sucesso sem conhecer fornecedor',async()=>{const result=await new BoundedWorkExecutor().run(request,new FakeWorkExecutor([{kind:'success',summary:'feito',resultReferences:['local:x']}]));expect(result).toEqual({kind:'succeeded',executorId:'fake',attempts:1,summary:'feito',resultReferences:['local:x']});});
  test('repete somente falha retryable até o limite',async()=>{const result=await new BoundedWorkExecutor().run(request,new FakeWorkExecutor([{kind:'failure',message:'transiente',retryable:true},{kind:'failure',message:'fim',retryable:true}]));expect(result).toEqual({kind:'failed',executorId:'fake',attempts:2,message:'fim'});});
  test('não repete falha terminal',async()=>{const result=await new BoundedWorkExecutor().run(request,new FakeWorkExecutor([{kind:'failure',message:'inválido',retryable:false}]));expect(result).toEqual({kind:'failed',executorId:'fake',attempts:1,message:'inválido'});});
  test('rejeição do executor vira resultado tipado',async()=>{const adapter:WorkExecutorAdapter={id:'broken',execute:()=>Promise.reject(new Error('quebrou'))};const result=await new BoundedWorkExecutor().run(request,adapter);expect(result).toEqual({kind:'failed',executorId:'broken',attempts:1,message:'quebrou'});});
  test('timeout de executor que ignora aborto registra encerramento sujo',async()=>{const adapter:WorkExecutorAdapter={id:'slow',execute:()=>new Promise(()=>{})};const result=await new BoundedWorkExecutor().run({...request,limits:{maxAttempts:2,timeoutMs:5,shutdownGraceMs:10}},adapter);expect(result).toEqual({kind:'timed_out',executorId:'slow',attempts:1,terminatedCleanly:false});});
  test('timeout aguarda executor reconhecer o aborto',async()=>{const adapter:WorkExecutorAdapter={id:'graceful',execute:(_,signal)=>new Promise(resolve=>signal.addEventListener('abort',()=>resolve({kind:'failure',message:'shutdown',retryable:false}),{once:true}))};const result=await new BoundedWorkExecutor().run({...request,limits:{maxAttempts:2,timeoutMs:5,shutdownGraceMs:1000}},adapter);expect(result).toEqual({kind:'timed_out',executorId:'graceful',attempts:1,terminatedCleanly:true});});
  test('propaga cancelamento com encerramento reconhecido',async()=>{const controller=new AbortController();const adapter:WorkExecutorAdapter={id:'waiting',execute:(_,signal)=>new Promise(resolve=>signal.addEventListener('abort',()=>resolve({kind:'failure',message:'abort',retryable:false}),{once:true}))};const pending=new BoundedWorkExecutor().run(request,adapter,controller.signal);controller.abort();expect(await pending).toEqual({kind:'cancelled',executorId:'waiting',attempts:1,terminatedCleanly:true});});
  test('cancelamento ignorado pelo executor registra encerramento sujo',async()=>{const controller=new AbortController();const adapter:WorkExecutorAdapter={id:'stuck',execute:()=>new Promise(()=>{})};const pending=new BoundedWorkExecutor().run({...request,limits:{maxAttempts:1,timeoutMs:5000,shutdownGraceMs:10}},adapter,controller.signal);controller.abort();expect(await pending).toEqual({kind:'cancelled',executorId:'stuck',attempts:1,terminatedCleanly:false});});
  test('recusa ciclos ilimitados',async()=>{await expect(new BoundedWorkExecutor().run({...request,limits:{maxAttempts:6,timeoutMs:50}},new FakeWorkExecutor([]))).rejects.toThrow('inválidos');});
});
