import {acceptResultForIntegration,buildProtectedIntegrationRequest,buildWorktreeHandoff,decideIntegration,produceResultForIntegration,beginProtectedIntegration,branchPublicationKey,nextProtectedIntegrationAction,parseBranchPublicationReceipt,projectBranchPublicationReceipt,recordBranchPublished,recordReviewRequestCreated,reviewRequestKey,type BranchPublicationReceipt,type ProtectedIntegrationRequest,type ReviewRequestReceipt,type WorkEvent,type WorktreeHandoffV1} from '.';
import type {Json} from '@anima/types';

const BASE='a'.repeat(40),COMMIT='b'.repeat(40);
const correlation=(origin:'executor'|'user')=>({workItemId:'work-1',attemptId:'attempt-1',approvedProposalVersion:3,origin});
const handoff=():WorktreeHandoffV1=>{const built=buildWorktreeHandoff({workItemId:'work-1',attemptId:'attempt-1',approvedProposalVersion:3,executorId:'worktree-v1',backendId:'fake',model:null,baseSha:BASE,branch:'anima-work/attempt-1',commitSha:COMMIT,status:'succeeded',changedFiles:['x.ts'],diffFiles:[{path:'x.ts',insertions:1,deletions:0}],gates:[{label:'test',command:'npm test',exitCode:0,outcome:'passed'}]});if(!built.ok)throw new Error(built.explanation);return built.value;};
const authorized=()=>{const produced=produceResultForIntegration({attempt:{attemptId:'attempt-1',workItemId:'work-1',approvedProposalVersion:3,status:'succeeded',executorId:'worktree-v1',startedAt:new Date('2026-08-09T00:00:00Z'),finishedAt:new Date('2026-08-09T00:01:00Z'),resultSummary:'feito',stopReason:'result_produced',handoffReference:'handoff-1'},workItemState:'review',resultCorrelation:correlation('executor'),handoff:{kind:'execution_result',reference:'handoff-1',resultEventId:'result-1'}});if(!produced.ok)throw new Error(produced.explanation);const accepted=acceptResultForIntegration(produced.value,{workItemState:'completed',decisionId:'accept-1',acceptedResultEventId:'result-1',correlation:correlation('user')});if(!accepted.ok)throw new Error(accepted.explanation);const decided=decideIntegration(accepted.value,{workItemState:'completed',decisionId:'authorize-1',decision:'authorize',correlation:correlation('user')});if(!decided.ok)throw new Error(decided.explanation);return decided.value;};
const request=():ProtectedIntegrationRequest=>{const built=buildProtectedIntegrationRequest(authorized(),handoff(),{providerId:'github',repositoryId:'anima/repo',remoteName:'origin',baseBranch:'main'});if(!built.ok)throw new Error(built.explanation);return built.value;};
const branch=(r=request(),overrides:Partial<BranchPublicationReceipt>={}):BranchPublicationReceipt=>({kind:'branch_publication',receiptId:'branch-receipt-1',idempotencyKey:branchPublicationKey(r),providerId:'github',repositoryId:'anima/repo',remoteName:'origin',remoteBranch:'anima-work/attempt-1',commitSha:COMMIT,baseBranch:'main',verifiedBaseSha:BASE,disposition:'created',...overrides});
const review=(r=request(),overrides:Partial<ReviewRequestReceipt>={}):ReviewRequestReceipt=>({kind:'review_request',receiptId:'review-receipt-1',idempotencyKey:reviewRequestKey(r),providerId:'github',repositoryId:'anima/repo',reviewId:'42',reviewReference:'https://example.invalid/review/42',sourceBranch:'anima-work/attempt-1',sourceCommitSha:COMMIT,baseBranch:'main',verifiedBaseSha:BASE,disposition:'created',...overrides});

describe('execução protegida de integração — protocolo puro',()=>{
  test('request carrega autorização, resultado, target, base, branch e commit explícitos',()=>expect(request()).toMatchObject({authorizationDecisionId:'authorize-1',acceptedResultEventId:'result-1',target:{providerId:'github',repositoryId:'anima/repo',remoteName:'origin',baseBranch:'main'},baseSha:BASE,localBranch:'anima-work/attempt-1',remoteBranch:'anima-work/attempt-1',commitSha:COMMIT}));
  test('sem autorização não deriva request',()=>{const boundary={...authorized(),status:'result_accepted' as const,integrationDecision:undefined};expect(buildProtectedIntegrationRequest(boundary,handoff(),{providerId:'github',repositoryId:'r',remoteName:'origin',baseBranch:'main'})).toMatchObject({ok:false,defect:'not_authorized'});});
  test('target inseguro ou implícito falha fechado',()=>expect(buildProtectedIntegrationRequest(authorized(),handoff(),{providerId:'github',repositoryId:'',remoteName:'origin',baseBranch:'main'})).toMatchObject({ok:false,defect:'invalid_target'}));
  test('happy path preserva fatos distintos',()=>{const initial=beginProtectedIntegration(request());expect(initial.status).toBe('integration_authorized');const pushed=recordBranchPublished(initial,branch());expect(pushed).toMatchObject({ok:true,value:{status:'branch_published'}});if(!pushed.ok)throw new Error();const opened=recordReviewRequestCreated(pushed.value,review());expect(opened).toMatchObject({ok:true,value:{status:'review_request_created'}});expect(opened).not.toHaveProperty('value.status','merged');});
  test('push passou e PR falhou permanece branch_published',()=>{const pushed=recordBranchPublished(beginProtectedIntegration(request()),branch());if(!pushed.ok)throw new Error();expect(pushed.value.status).toBe('branch_published');expect(nextProtectedIntegrationAction(pushed.value)).toBe('inspect_or_create_review_request');});
  test('branch remota já existente no commit esperado reconcilia',()=>expect(recordBranchPublished(beginProtectedIntegration(request()),branch(request(),{disposition:'already_existed'}))).toMatchObject({ok:true,value:{status:'branch_published'}}));
  test.each([['wrong repo',{repositoryId:'outro/repo'}],['wrong branch',{remoteBranch:'anima-work/outra'}],['wrong base',{verifiedBaseSha:'c'.repeat(40)}],['wrong commit',{commitSha:'d'.repeat(40)}]] as const)('%s é recusado',(_,override)=>expect(recordBranchPublished(beginProtectedIntegration(request()),branch(request(),override))).toMatchObject({ok:false,defect:'receipt_mismatch'}));
  test('mesmo commit sob branch errada é recusado',()=>expect(recordBranchPublished(beginProtectedIntegration(request()),branch(request(),{remoteBranch:'anima-work/errada',commitSha:COMMIT}))).toMatchObject({ok:false,defect:'receipt_mismatch'}));
  test('duplicate receipt é idempotente e receipt divergente conflita',()=>{const first=recordBranchPublished(beginProtectedIntegration(request()),branch());if(!first.ok)throw new Error();expect(recordBranchPublished(first.value,branch())).toEqual(first);expect(recordBranchPublished(first.value,branch(request(),{receiptId:'outro'}))).toMatchObject({ok:false,defect:'receipt_conflict'});});
  test('created e already_existed são a mesma identidade verificável em retry',()=>{const first=recordBranchPublished(beginProtectedIntegration(request()),branch());if(!first.ok)throw new Error();expect(recordBranchPublished(first.value,branch(request(),{disposition:'already_existed'}))).toEqual(first);});
  test('receipt logicamente idêntico independe da ordem das propriedades',()=>{const original=branch();const reordered={disposition:original.disposition,verifiedBaseSha:original.verifiedBaseSha,baseBranch:original.baseBranch,commitSha:original.commitSha,remoteBranch:original.remoteBranch,remoteName:original.remoteName,repositoryId:original.repositoryId,providerId:original.providerId,idempotencyKey:original.idempotencyKey,receiptId:original.receiptId,kind:original.kind};const first=recordBranchPublished(beginProtectedIntegration(request()),original);if(!first.ok)throw new Error();expect(recordBranchPublished(first.value,reordered)).toEqual(first);});
  test('read model aceita somente fato persistido integralmente correlacionado',()=>{const r=request(),value=branch(r);const payload=JSON.parse(JSON.stringify({schema_version:1,data:{authorization_decision_id:'authorize-1',accepted_result_event_id:'result-1',attempt_id:'attempt-1',receipt:value}})) as Json;const event:WorkEvent={id:'published-1',workItemId:'work-1',type:'branch_published',author:'system',proposalVersion:3,payload,occurredAt:new Date()};expect(projectBranchPublicationReceipt([event],r)).toEqual({ok:true,value});expect(projectBranchPublicationReceipt([{...event,author:'user'}],r)).toMatchObject({ok:false,defect:'receipt_mismatch'});expect(projectBranchPublicationReceipt([event,{...event,id:'published-2'}],r)).toMatchObject({ok:false,defect:'receipt_conflict'});});
  test('parser de receipt falha fechado em identidade incompleta',()=>{const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Json;expect(parseBranchPublicationReceipt(json(branch()))).toEqual(branch());expect(parseBranchPublicationReceipt(json({...branch(),baseBranch:''}))).toBeNull();expect(parseBranchPublicationReceipt(json({...branch(),remoteBranch:'main..lock'}))).toBeNull();});
  test('PR antes do push é impossível',()=>expect(recordReviewRequestCreated(beginProtectedIntegration(request()),review())).toMatchObject({ok:false,defect:'step_out_of_order'}));
  test('PR já existente correto reconcilia sem duplicar',()=>{const pushed=recordBranchPublished(beginProtectedIntegration(request()),branch());if(!pushed.ok)throw new Error();expect(recordReviewRequestCreated(pushed.value,review(request(),{disposition:'already_existed'}))).toMatchObject({ok:true,value:{status:'review_request_created'}});});
  test.each([['repo',{repositoryId:'outro/repo'}],['source branch',{sourceBranch:'anima-work/outra'}],['source commit',{sourceCommitSha:'d'.repeat(40)}],['base branch',{baseBranch:'develop'}],['base sha',{verifiedBaseSha:'c'.repeat(40)}]] as const)('PR com %s divergente falha fechado',(_,override)=>{const pushed=recordBranchPublished(beginProtectedIntegration(request()),branch());if(!pushed.ok)throw new Error();expect(recordReviewRequestCreated(pushed.value,review(request(),override))).toMatchObject({ok:false,defect:'receipt_mismatch'});});
  test('retry/crash reconcilia por receipt e nunca infere merge',()=>{const r=request();const recovered=recordBranchPublished(beginProtectedIntegration(r),branch(r,{disposition:'already_existed'}));if(!recovered.ok)throw new Error();const pr=recordReviewRequestCreated(recovered.value,review(r,{disposition:'already_existed'}));if(!pr.ok)throw new Error();expect(nextProtectedIntegrationAction(pr.value)).toBe('await_human_merge_decision');expect(pr.value.status).toBe('review_request_created');expect(JSON.stringify(pr.value)).not.toContain('integrated');});
});
