import { WorkOrchestrationService, type IntegrationDecisionOutcome, type WorkContextSnapshot, type WorkEvent, type WorkItem, type WorkOperationResult, type WorkOrchestrationRepository } from '.';
const decisionSuccess = (): Promise<WorkOperationResult<IntegrationDecisionOutcome>> => Promise.resolve({ ok: true, value: { action: 'recorded', decision: 'authorize', eventSeq: 1 } });
const item = { id:'i', userId:'u', sourceMessageId:'m', state:'proposed', impactLevel:'low', capability:'planning', originalRequest:'x', intent:{}, proposal:{schemaVersion:1,data:{summary:'s',objective:'o',includedScope:[],excludedScope:[],expectedEffects:[],risks:[]}},proposalVersion:1,createdAt:new Date(),updatedAt:new Date()} satisfies WorkItem;
const success = (): Promise<WorkOperationResult<WorkItem>> => Promise.resolve({ ok: true, value: item });
const eventSuccess = (): Promise<WorkOperationResult<readonly WorkEvent[]>> => Promise.resolve({ ok: true, value: [] });
const context = { id:'c',workItemId:'i',version:1,references:[{kind:'message',id:'m'}],createdAt:new Date() } satisfies WorkContextSnapshot;
const contextSuccess = (): Promise<WorkOperationResult<WorkContextSnapshot>> => Promise.resolve({ok:true,value:context});
const contextsSuccess = (): Promise<WorkOperationResult<readonly WorkContextSnapshot[]>> => Promise.resolve({ok:true,value:[context]});
const repository = (): WorkOrchestrationRepository => ({ createProposal:jest.fn(success), reviseProposal:jest.fn(success),requestProposalRevision:jest.fn(success),resolveApproval:jest.fn(success),startWork:jest.fn(success),releaseManualWork:jest.fn(success),submitResult:jest.fn(success),startExecution:jest.fn(success),finishExecution:jest.fn(success),reviewResult:jest.fn(success),decideIntegration:jest.fn(decisionSuccess),attachContext:jest.fn(contextSuccess),getItem:jest.fn(success),findItemsBySourceMessageId:jest.fn(async():Promise<WorkOperationResult<readonly WorkItem[]>>=>({ok:true,value:[item]})),findResumableWorkItems:jest.fn(async():Promise<WorkOperationResult<readonly WorkItem[]>>=>({ok:true,value:[item]})),listEvents:jest.fn(eventSuccess),listEventsByType:jest.fn(eventSuccess),listContexts:jest.fn(contextsSuccess) });
describe('WorkOrchestrationService',()=>{
  test('encaminha cada comando exatamente uma vez',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const base={workItemId:'i',expectedProposalVersion:1}; await s.resolveApproval({...base,decision:{type:'approve'}}); await s.startWork(base); await s.releaseManualWork(base); await s.submitResult({...base,result:{summary:'feito',resultReferences:[]}}); await s.reviewResult({...base,reviewedResultEventId:'e1',decision:{type:'accept'}}); await s.attachContext({...base,references:[{kind:'message',id:'m'}]}); expect(r.resolveApproval).toHaveBeenCalledTimes(1); expect(r.startWork).toHaveBeenCalledTimes(1); expect(r.releaseManualWork).toHaveBeenCalledTimes(1); expect(r.submitResult).toHaveBeenCalledTimes(1); expect(r.reviewResult).toHaveBeenCalledTimes(1); expect(r.attachContext).toHaveBeenCalledTimes(1); });
  test('não chama repositório para entrada inválida',async()=>{ const r=repository(); const result=await new WorkOrchestrationService(r).startWork({workItemId:'i',expectedProposalVersion:0}); expect(result.ok).toBe(false); expect(r.startWork).not.toHaveBeenCalled(); });
  test('preserva erro sem retry',async()=>{ const r=repository(); const start = r.startWork as jest.MockedFunction<typeof r.startWork>; start.mockResolvedValue({ok:false,error:{code:'version_conflict',message:'Conflito.',retryable:false}}); const result=await new WorkOrchestrationService(r).startWork({workItemId:'i',expectedProposalVersion:1}); expect(result.ok).toBe(false); expect(r.startWork).toHaveBeenCalledTimes(1); });
  test('valida desfecho de execução antes de persistir',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const base={workItemId:'i',expectedProposalVersion:1,executionId:'e'}; const invalid=await s.finishExecution({...base,outcome:{kind:'failed',executorId:'fake',attempts:-1,message:'x'}}); expect(invalid.ok).toBe(false); expect(r.finishExecution).not.toHaveBeenCalled(); const valid=await s.finishExecution({...base,outcome:{kind:'succeeded',executorId:'fake',attempts:1,summary:'feito',resultReferences:[]}}); expect(valid.ok).toBe(true); expect(r.finishExecution).toHaveBeenCalledTimes(1); });
  test('recusa início de execução sem identificador ou executor',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const missing=await s.startExecution({workItemId:'i',expectedProposalVersion:1,executionId:' ',executorId:'fake'}); expect(missing.ok).toBe(false); expect(r.startExecution).not.toHaveBeenCalled(); });
  test('encaminha uma decisão de integração válida',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const result=await s.decideIntegration({workItemId:'i',expectedProposalVersion:1,acceptedResultEventId:'e1',decision:'authorize',decisionId:'d1'}); expect(result.ok).toBe(true); expect(r.decideIntegration).toHaveBeenCalledTimes(1); });
  test('recusa decisão de integração inválida sem chamar o repositório',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const base={workItemId:'i',expectedProposalVersion:1,acceptedResultEventId:'e1',decisionId:'d1'} as const; expect((await s.decideIntegration({...base,decision:'maybe' as 'authorize'})).ok).toBe(false); expect((await s.decideIntegration({...base,decision:'authorize',acceptedResultEventId:' '})).ok).toBe(false); expect((await s.decideIntegration({...base,decision:'authorize',decisionId:' '})).ok).toBe(false); expect((await s.decideIntegration({...base,decision:'authorize',expectedProposalVersion:0})).ok).toBe(false); expect(r.decideIntegration).not.toHaveBeenCalled(); });
  test('listEventsByType encaminha um tipo válido e recusa tipo vazio sem chamar o repositório',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const ok=await s.listEventsByType('host_observed_gate_evidence_recorded'); expect(ok.ok).toBe(true); expect(r.listEventsByType).toHaveBeenCalledTimes(1); expect(r.listEventsByType).toHaveBeenCalledWith('host_observed_gate_evidence_recorded'); const bad=await s.listEventsByType('' as WorkEvent['type']); expect(bad.ok).toBe(false); expect(r.listEventsByType).toHaveBeenCalledTimes(1); });
});
