import { WorkOrchestrationService, type WorkContextSnapshot, type WorkEvent, type WorkItem, type WorkOperationResult, type WorkOrchestrationRepository } from '.';
const item = { id:'i', userId:'u', sourceMessageId:'m', state:'proposed', impactLevel:'low', capability:'planning', originalRequest:'x', intent:{}, proposal:{schemaVersion:1,data:{summary:'s',objective:'o',includedScope:[],excludedScope:[],expectedEffects:[],risks:[]}},proposalVersion:1,createdAt:new Date(),updatedAt:new Date()} satisfies WorkItem;
const success = (): Promise<WorkOperationResult<WorkItem>> => Promise.resolve({ ok: true, value: item });
const eventSuccess = (): Promise<WorkOperationResult<readonly WorkEvent[]>> => Promise.resolve({ ok: true, value: [] });
const context = { id:'c',workItemId:'i',version:1,references:[{kind:'message',id:'m'}],createdAt:new Date() } satisfies WorkContextSnapshot;
const contextSuccess = (): Promise<WorkOperationResult<WorkContextSnapshot>> => Promise.resolve({ok:true,value:context});
const contextsSuccess = (): Promise<WorkOperationResult<readonly WorkContextSnapshot[]>> => Promise.resolve({ok:true,value:[context]});
const repository = (): WorkOrchestrationRepository => ({ createProposal:jest.fn(success), reviseProposal:jest.fn(success),resolveApproval:jest.fn(success),startWork:jest.fn(success),submitResult:jest.fn(success),reviewResult:jest.fn(success),attachContext:jest.fn(contextSuccess),getItem:jest.fn(success),findItemsBySourceMessageId:jest.fn(async():Promise<WorkOperationResult<readonly WorkItem[]>>=>({ok:true,value:[item]})),listEvents:jest.fn(eventSuccess),listContexts:jest.fn(contextsSuccess) });
describe('WorkOrchestrationService',()=>{
  test('encaminha cada comando exatamente uma vez',async()=>{ const r=repository(); const s=new WorkOrchestrationService(r); const base={workItemId:'i',expectedProposalVersion:1}; await s.resolveApproval({...base,decision:{type:'approve'}}); await s.startWork(base); await s.submitResult({...base,result:{summary:'feito',resultReferences:[]}}); await s.reviewResult({...base,decision:{type:'accept'}}); await s.attachContext({...base,references:[{kind:'message',id:'m'}]}); expect(r.resolveApproval).toHaveBeenCalledTimes(1); expect(r.startWork).toHaveBeenCalledTimes(1); expect(r.submitResult).toHaveBeenCalledTimes(1); expect(r.reviewResult).toHaveBeenCalledTimes(1); expect(r.attachContext).toHaveBeenCalledTimes(1); });
  test('não chama repositório para entrada inválida',async()=>{ const r=repository(); const result=await new WorkOrchestrationService(r).startWork({workItemId:'i',expectedProposalVersion:0}); expect(result.ok).toBe(false); expect(r.startWork).not.toHaveBeenCalled(); });
  test('preserva erro sem retry',async()=>{ const r=repository(); const start = r.startWork as jest.MockedFunction<typeof r.startWork>; start.mockResolvedValue({ok:false,error:{code:'version_conflict',message:'Conflito.',retryable:false}}); const result=await new WorkOrchestrationService(r).startWork({workItemId:'i',expectedProposalVersion:1}); expect(result.ok).toBe(false); expect(r.startWork).toHaveBeenCalledTimes(1); });
});
