import { resolveCliIdentity } from '@/cli/identity';
import { createWorkOrchestrationService } from '@/lib/work-orchestration/server';
const ITEM='571d29be-2912-4775-80e0-ba8df1e00a5e'; const VERSION=1;
const SCOPE=['apps/web/lib/work-orchestration/post-turn-observation.ts','apps/web/lib/work-orchestration/post-turn-observation.test.ts','apps/web/lib/work-orchestration/autonomous-backlog-deps.ts','apps/web/lib/work-orchestration/autonomous-backlog-deps-router.test.ts'];
const E1='E1. Nenhuma API, RPC ou tipo de settlement inexistente é introduzido; são proibidos settle_openai_actual_cost, actualCostUsd vindo do caller, nova tabela/migration/protocolo e any para contornar contratos.';
const E2='E2. O diff reutiliza ProviderPricingV1, settleOpenAIActualCostReservation, OpenAISettlementAuditV1 e settlePaidComputeBudgetReservation com adapter {reservationId, settled: audit.actualCost, costSource}.';
const E3='E3. autonomous-backlog-deps.ts muda materialmente e o caller buildProjectBacklogCycleDeps(...).runTurn correlaciona lease provider-api:<attemptId>, reservation, usage terminal provider-reported, provider/model/cohort/pricing até adapter→primitive→store.';
const E4='E4. O strong harness host-side, controlado fora do output do coder, passa contra o output final.';
const E5='E5. O mesmo strong harness falha contra 61eb2eb7ab1b4091e1a53604ef11b560ef99561f e 5fad66796af8ceeb8ad3f175dfeba911c324caec.';
const E6='E6. Testes do coder são evidência adicional, nunca a única fonte; cobrem pricing conhecido/null, usage ausente, pricing inválido, over-reservation, replay, incompatibilidades provider/model/moeda, correlação e Ollama/RunPod intocados.';
const E7=`E7. Somente ${SCOPE.join(', ')} podem mudar.`;
async function main():Promise<void>{const identity=await resolveCliIdentity();if(!identity.ok)throw new Error(identity.error);const service=createWorkOrchestrationService(identity.identity.client);const current=await service.getItem(ITEM);if(!current.ok)throw new Error(current.error.message);if(current.value.state!=='proposed'||current.value.proposalVersion!==VERSION)throw new Error(`estado inesperado ${current.value.state} v${current.value.proposalVersion}`);const raw=current.value.intent.execution_spec;if(typeof raw!=='object'||raw===null||Array.isArray(raw))throw new Error('spec ausente');
 const criteria=[
 {label:'Harness focal das APIs reais',command:'npm test --workspace=@anima/web -- post-turn-observation.test.ts openai-actual-cost-settlement.test.ts paid-compute-authorization-store.test.ts',proof:'gate',covers:[E1,E2,E4,E5,E6]},
 {label:'Harness do caller vivo',command:'npm test --workspace=@anima/web -- autonomous-backlog-deps-router.test.ts',proof:'gate',covers:[E3,E4,E5,E6]},
 {label:'Typecheck web estrito',command:'npm run typecheck --workspace=@anima/web',proof:'gate',covers:[E1,E2,E3]},
 {label:'Contenção observada pelo host',proof:'scope',covers:[E7]},
 ];
 const objective='Refaça B1/B2/B3 usando como especificação técnica read-only o diff ccb7dcc..0bea4c8 (af313c3 validado): resolveOpenAIActualCostSettlementFacts lê paid_compute_budget_events pelo lease provider-api:<attemptId>, projeta usage terminal das coderObservations e recebe ProviderPricingV1|null; persistPostTurnHostObservations chama settleOpenAIActualCostReservation e adapta OpenAISettlementAuditV1 para settlePaidComputeBudgetReservation(client,{reservationId,settled:audit.actualCost,costSource}). buildProjectBacklogCycleDeps(...).runTurn monta reservation/usage/provider/model/cohort/pricing e passa ao adapter. Pricing null não liquida. Proibido inventar RPC/API/tabela/migration/actualCostUsd/protocolo/nome substituto ou any; se API faltar, pare com evidência. A referência é exemplo, não deve ser promovida, cherry-picked, merged ou copiada automaticamente.';
 const revised=await service.reviseProposal({workItemId:ITEM,expectedProposalVersion:VERSION,intent:{...current.value.intent,execution_spec:{...raw,correction_scope:{rework_scope:SCOPE,remaining_scope:SCOPE,effective_scope:SCOPE},validation_criteria:criteria}},proposal:{schemaVersion:1,data:{summary:'Correction B1/B2/B3 com APIs reais e harness host-side não-gameável.',objective,includedScope:SCOPE,excludedScope:['packages/core','supabase/migrations','nova RPC/tabela/protocolo','reservas históricas','Ollama','RunPod','Verifier v2','merge','push','deploy','origin/main'],expectedEffects:[E1,E2,E3,E4,E5,E6,E7],risks:['Se qualquer API real necessária estiver ausente, parar com evidência concreta em vez de inventar contrato.','Os gates do output não substituem o overlay host-side dos testes fortes de 0bea4c8.']}}});if(!revised.ok)throw new Error(`${revised.error.code}: ${revised.error.message}`);console.log(JSON.stringify({id:revised.value.id,state:revised.value.state,version:revised.value.proposalVersion,intent:revised.value.intent,proposal:revised.value.proposal},null,2));}
void main().catch(error=>{console.error(error instanceof Error?error.stack??error.message:String(error));process.exitCode=1;});
