process.env.ANIMA_AI_PROVIDER='openai'; process.env.ANIMA_WORKTREE_CODER_BACKEND='openai';
import type { CreateWorkProposalCommand } from '@anima/core';
import { resolveCliIdentity } from '@/cli/identity';
import { OpenAIProjectWorkPlanner, planExecutableProjectWork } from '@/lib/ai/project-work-planner';
import { createOpenAIPlannerAdmission } from '@/lib/work-orchestration/openai-paid-compute';
import { grantPaidComputeAuthorization } from '@/lib/work-orchestration/paid-compute-authorization-store';
import { createWorkOrchestrationService } from '@/lib/work-orchestration/server';
import { readAuthorizedBaseSha, readExecutionContract } from '@/lib/work-orchestration/executor-selection';
const MODEL=process.env.OPENAI_MODEL??'gpt-5.6-terra', CEILING=1.25;
const MESSAGE=[
 'Recovery governado do Ponto 2 OpenAI actual-cost settlement. Predecessor falho 8021c1ce-6ad6-4038-b30e-183805f2e7f9, attempt 8e51abf5-34e6-4601-8541-0801f5c6d0b0, checkpoint branch anima-work/8e51abf5-34e6-4601-8541-0801f5c6d0b0 commit f387c6139845970614d9ec61162d64b836603086.',
 'O replan antigo foi corretamente recusado como not_minimal_test_unit. Produza um Work Item novo e autocontido que reimplemente apenas o recorte necessário na base autorizada, usando o checkpoint como diagnóstico, não como resultado confiável.',
 'Falhas obrigatórias a corrigir: teste importou vitest em workspace Jest; callback settleActualCost ficou opcional sem chamador; reservationId, usage e pricing não chegam ao terminal; trilha auditável não é persistida.',
 'Implemente wiring real reservation admission -> attempt OpenAI -> usage provider-reported agregada -> terminal pós-evidência -> calculateApiAttemptCost com ProviderPricingV1 explícito/versionado -> settlePaidComputeBudgetReservation. Use a API canônica do store, não callback paralelo incompatível. Persista trilha auditável usando o canal de evidence/evento já existente; sem migration se ele bastar.',
 'Fail closed: reserved != settled; nunca ceiling como custo; faltar usage/pricing/correlação ou custo acima da reserva mantém reserva aberta; replay idempotente; cost_source estimated somente com fórmula e sourceRef/effectiveFrom auditáveis. Não liquide reservas históricas neste item.',
 'Testes Jest reais devem provar sucesso uma vez, replay, usage ausente, pricing ausente/inválido, over-reservation, moeda/model/provider incompatíveis, Ollama intocado e RunPod intocado. Inclua um gate Jest focal e typecheck/build proporcional; não use apenas build como substituto dos testes.',
 'Escopo máximo: packages/core/src/compute-economics.ts e teste; apps/web/lib/work-orchestration/openai-paid-compute.ts e teste; novo openai-actual-cost-settlement.ts e teste; post-turn-observation.ts e teste; autonomous-backlog-deps.ts e um teste focal NOVO ou existente que não seja autonomous-backlog-deps-router.test.ts. Se a passagem da reservationId exigir gpt-coder ou worktree-executor, inclua os respectivos arquivos e testes explicitamente. Selecione o subconjunto mínimo suficiente.',
 'Exclua autonomous-backlog-deps-router.test.ts, Verifier v2, Ponto 1, migrations, reservas c0edc775/8e51abf5, integração, merge, deploy e origin/main. expected_effects e covers devem ser exatamente alinhados.',
].join(' ');
const log=(v:unknown)=>console.log(JSON.stringify(v,null,2));
async function main(){const id=await resolveCliIdentity();if(!id.ok)throw new Error(id.error);const{client,userId}=id.identity;const svc=createWorkOrchestrationService(client);const baseSha=await readAuthorizedBaseSha();if(!baseSha)throw new Error('base ausente');const source=await client.from('ai_conversations').insert({user_id:userId,role:'user',content:MESSAGE}).select('id').single();if(source.error||!source.data)throw new Error(source.error?.message??'source');const cmd:CreateWorkProposalCommand={sourceMessageId:source.data.id,impactLevel:'low',capability:'programming',intent:{planner:'admission_placeholder'},proposal:{schemaVersion:1,data:{summary:'Recovery placeholder do Ponto 2.',objective:'Concluir settlement OpenAI fim a fim.',includedScope:['(planner forte define)'],excludedScope:['Ponto 1','Verifier v2','origin/main'],expectedEffects:['Planner forte produzirá proposta terminal.'],risks:['Placeholder não executável.']}}};const created=await svc.createProposal(cmd);if(!created.ok)throw new Error(`${created.error.code}:${created.error.message}`);const workItemId=created.value.id;const grant=await grantPaidComputeAuthorization(client,{providerId:'openai',nodeId:'openai-api',resourceClass:`provider_api:${MODEL}`,workItemId,maxDurationMs:45*60_000,maxCost:{currency:'USD',amount:CEILING},validFrom:new Date(Date.now()-30_000).toISOString(),validUntil:new Date(Date.now()+86_400_000).toISOString()});if(!grant.ok)throw new Error(`${grant.code}:${grant.message}`);const planned=await planExecutableProjectWork(MESSAGE,{sourceMessageId:source.data.id,impactLevel:'low',capability:'programming',intent:{},proposal:cmd.proposal},new OpenAIProjectWorkPlanner({admission:createOpenAIPlannerAdmission(client,workItemId),userId,model:MODEL}));if(!planned.ok)throw new Error(planned.message);const revised=await svc.reviseProposal({workItemId,expectedProposalVersion:created.value.proposalVersion,intent:planned.command.intent,proposal:planned.command.proposal});if(!revised.ok)throw new Error(`${revised.error.code}:${revised.error.message}`);const criteria=((planned.command.intent as {execution_spec?:{validation_criteria?:{label:string;command?:string;proof?:string;covers?:string[]}[]}}).execution_spec?.validation_criteria)??[];const effects=planned.command.proposal.data.expectedEffects??[];const set=new Set(effects),unknown=criteria.flatMap(c=>(c.covers??[]).filter(x=>!set.has(x))),uncovered=effects.filter(e=>!criteria.some(c=>(c.covers??[]).includes(e)));log({workItemId,version:revised.value.proposalVersion,authorizationId:grant.authorizationId,baseSha,coderBackend:readExecutionContract(planned.command.intent).coderBackend,includedScope:planned.command.proposal.data.includedScope,excludedScope:planned.command.proposal.data.excludedScope,expectedEffects:effects,criteria,ALIGNMENT:{unknown,uncovered,aligned:!unknown.length&&!uncovered.length}})}
void main().catch(e=>{console.error(e instanceof Error?e.stack??e.message:String(e));process.exitCode=1});
