// Capability Registry V0 — o modelo hand-authored das capacidades do Anima.
//
// Este é o V0 declarativo previsto no item 4/10 do plano do Capability Map. Ele
// NÃO é a árvore visual: é o modelo que a tela `/evolution` projeta. No futuro,
// este registro manual pode ser SUBSTITUÍDO por um Capability Proof Engine que
// deriva maturidade e provas de event log + attempts + verifier + runtime — sem
// mudar o contrato de `Capability` nem a UI (ver capability-map.ts).
//
// Regra de honestidade: uma capacidade só recebe estado forte
// (`proven`/`operational`/`autonomous`) quando há EVIDÊNCIA REAL no repositório.
// `proofRefs` apontam para commits, testes, attempts, marcos e registros que
// existem de fato. Na dúvida, o estado é rebaixado. Capacidades futuras aparecem
// como `projected`/`specified` — nunca como se já existissem.

import { buildCapabilityGraph, type Capability, type CapabilityGraph } from './capability-map';

export const ANIMA_CAPABILITY_REGISTRY_V0: Capability[] = [
  // ─── COMPREENSÃO ──────────────────────────────────────────────────────────
  {
    id: 'understanding.entities',
    name: 'Entidades e relações',
    description: 'Extrair entidades (pessoas, lugares, projetos, hábitos) e derivar vínculos entre elas e os pilares.',
    domain: 'understanding',
    maturity: 'operational',
    dependsOn: ['memory.persistence', 'understanding.pillars'],
    meaning:
      'O Anima reconhece coisas do mundo do usuário como entidades de primeira classe e as liga entre si e a pilares — um tecido navegável, não texto solto.',
    advancement:
      'Autonomia: manter precisão de extração e de relações sob volume real, sem revisão humana, e reconciliar duplicatas sozinho.',
    proofRefs: [
      { kind: 'route', ref: 'apps/web/app/api/ai/extract-entities', note: 'rota de extração de entidades' },
      { kind: 'route', ref: 'apps/web/app/(app)/graph/page.tsx', note: 'entidades e arestas relation/cooccurrence no grafo' },
    ],
  },
  {
    id: 'understanding.pillars',
    name: 'Pilares (XP e níveis)',
    description: 'Modelar áreas de vida como pilares com XP, níveis e progresso.',
    domain: 'understanding',
    maturity: 'operational',
    dependsOn: ['memory.persistence'],
    meaning: 'A evolução do usuário é medida por pilar — o substrato de "jornadas de evolução" do manifesto.',
    advancement: 'Já operacional; próximo salto é o Anima ajustar pesos/curvas por evidência sem configuração manual.',
    proofRefs: [
      { kind: 'test', ref: 'packages/core/src/levels.test.ts' },
      { kind: 'doc', ref: 'apps/web/app/(app)/home/_components/LifeRadar.tsx' },
    ],
  },
  {
    id: 'understanding.pillar-inference',
    name: 'Inferência de pilares',
    description: 'Propor pilares emergentes e confirmá-los/descartá-los com o usuário.',
    domain: 'understanding',
    maturity: 'proven',
    dependsOn: ['understanding.pillars', 'understanding.entities'],
    meaning: 'O Anima percebe áreas de vida que estão surgindo e as sugere, em vez de exigir que o usuário as declare.',
    advancement: 'Reproduzir a proposta de pilares de forma confiável e reduzir falsos positivos sem revisão constante.',
    proofRefs: [
      { kind: 'route', ref: 'apps/web/app/api/pillars/confirm' },
      { kind: 'doc', ref: 'apps/web/app/(app)/home/_components/PendingPillarsWidget.tsx' },
    ],
  },
  {
    id: 'understanding.projects',
    name: 'Projetos e intake',
    description: 'Capturar/estruturar ideias (Project Intake) e representar projetos com advisor, snapshot operacional e drilldown.',
    domain: 'understanding',
    maturity: 'proven',
    dependsOn: ['memory.persistence'],
    meaning: 'Uma ideia crua vira um objeto de projeto estruturado que o sistema raciocina, acompanha, aconselha e resume — cidadão de primeira classe.',
    advancement: 'Comprovar intake conversacional e acompanhamento contínuo de projetos de domínios diferentes (não só o próprio Anima).',
    proofRefs: [
      { kind: 'test', ref: 'packages/core/src/project-intake.test.ts' },
      { kind: 'test', ref: 'packages/core/src/project-advisor.test.ts' },
      { kind: 'test', ref: 'packages/core/src/project-operational-snapshot.test.ts' },
    ],
  },
  {
    id: 'understanding.world-model',
    name: 'World model',
    description: 'Um modelo unificado do mundo do usuário que se reorganiza sozinho quando novos dados chegam.',
    domain: 'understanding',
    maturity: 'projected',
    dependsOn: ['understanding.entities', 'understanding.pillar-inference', 'understanding.projects', 'memory.narrative-memory'],
    target: { description: 'Compreensão emergente e auto-organizada do mundo do usuário.' },
    meaning: 'O Anima deixa de guardar fatos isolados e passa a manter um modelo vivo que reorganiza conceitos por conta própria.',
    advancement: 'Falta o mecanismo de reorganização emergente e a memória narrativa que o alimenta.',
  },

  // ─── MEMÓRIA ────────────────────────────────────────────────────────────────
  {
    id: 'memory.persistence',
    name: 'Persistência',
    description: 'Armazenar de forma durável entradas, notas, entidades e estado sob RLS por usuário.',
    domain: 'memory',
    maturity: 'operational',
    dependsOn: [],
    meaning: 'A base de tudo: nada evolui se não persiste. Supabase com RLS por usuário guarda o estado do Anima.',
    advancement: 'Já operacional; evolução é resiliência multi-nó/portátil (ver Marco 004) sem cópia indiscriminada.',
    proofRefs: [{ kind: 'doc', ref: 'supabase/migrations', note: 'schema versionado + RLS' }],
  },
  {
    id: 'memory.event-history',
    name: 'Eventos e histórico',
    description: 'Registrar eventos append-only (work_events, ledger) e expor histórico navegável.',
    domain: 'memory',
    maturity: 'operational',
    dependsOn: ['memory.persistence'],
    meaning: 'O passado do sistema é recuperável só pelo repositório/estado — base para auditoria, retomada e futura inferência de provas.',
    advancement: 'Já operacional; próximo uso é alimentar o Capability Proof Engine a partir destes eventos.',
    proofRefs: [
      { kind: 'test', ref: 'packages/core/src/economic-observations.test.ts', note: 'event store por coorte' },
      { kind: 'route', ref: 'apps/web/app/(app)/history' },
    ],
  },
  {
    id: 'memory.context-recovery',
    name: 'Recuperação de contexto',
    description: 'Embutir entradas e recuperar contexto relevante por similaridade.',
    domain: 'memory',
    maturity: 'proven',
    dependsOn: ['memory.persistence'],
    meaning: 'O Anima traz de volta o que é relevante para o momento, em vez de depender de o usuário lembrar onde algo está.',
    advancement: 'Comprovar relevância consistente sob volume e integrar à memória narrativa.',
    proofRefs: [{ kind: 'route', ref: 'apps/web/app/api/ai/embed-entry' }],
  },
  {
    id: 'memory.continuity',
    name: 'Continuidade e retomada',
    description: 'Retomar trabalho de um checkpoint durável após interrupção (orçamento, decomposição).',
    domain: 'memory',
    maturity: 'proven',
    dependsOn: ['memory.event-history', 'governance.attempt'],
    meaning: 'Uma interrupção não perde trabalho: o Anima retoma exatamente de onde parou, preservando o que já foi verificado.',
    advancement: 'Reproduzir retomada de forma rotineira em cenários variados até virar operacional.',
    proofRefs: [
      { kind: 'commit', ref: 'e090013', note: 'retomada da worktree do checkpoint na decomposição' },
      { kind: 'milestone', ref: 'docs/marcos/008-dev-local-v1-review-rework-incremental.md' },
    ],
  },
  {
    id: 'memory.narrative-memory',
    name: 'Memória narrativa',
    description: 'Uma memória que narra a evolução do usuário e reconcilia contradições ao longo do tempo, não só guarda registros.',
    domain: 'memory',
    maturity: 'projected',
    dependsOn: ['memory.context-recovery', 'memory.event-history'],
    target: { description: 'Memória que relaciona no tempo, narra a evolução e resolve contradições — base da proatividade cognitiva.' },
    meaning: 'O Anima passa de "receber → armazenar → exibir" para "lembrar → relacionar → refletir", percebendo e reconciliando conflitos (Prisma como capacidade interna).',
    advancement: 'Falta a síntese narrativa sobre o histórico e a detecção/resolução de contradições que a mantém coerente.',
  },

  // ─── AGÊNCIA ────────────────────────────────────────────────────────────────
  {
    id: 'agency.edit-file',
    name: 'Ler e editar arquivo',
    description: 'O coder lê arquivos do workspace e edita código por âncora exata, robusto a CRLF e a âncoras ambíguas.',
    domain: 'agency',
    maturity: 'operational',
    dependsOn: ['agency.isolated-workspace'],
    meaning: 'READ e WRITE são a base da agência de código: o coder enxerga o que vai mudar e altera com precisão cirúrgica.',
    advancement: 'Operacional; a rodada de leitura já vira orçamento no Harness V3 e endurecimentos (harness policy + AST) mitigam edições fora do alvo.',
    proofRefs: [
      { kind: 'commit', ref: '6adce1c', note: 'desambiguação de âncora por evidência (in_lines)' },
      { kind: 'commit', ref: '97c042d', note: 'edição agnóstica a fim de linha (CRLF↔LF)' },
      { kind: 'test', ref: 'apps/web/lib/work-orchestration/harness/deepseek-harness-runtime.test.ts' },
    ],
  },
  {
    id: 'agency.run-tests',
    name: 'Executar testes e comandos governados',
    description: 'Rodar testes escopados ao workspace como gate (host-observed) e comandos sob política (git read-only, rede negada).',
    domain: 'agency',
    maturity: 'proven',
    dependsOn: ['agency.isolated-workspace', 'governance.authority'],
    meaning: 'EXEC/TEST é uma autoridade distinta de READ/WRITE: o Anima não confia no próprio código sem prova, e comandos rodam num envelope explícito.',
    advancement:
      'Gates são operacionais; o loop governado edit→test→exec→submit do Harness V3 ainda espera prova viva end-to-end e sandbox de rede em nível de kernel.',
    proofRefs: [
      { kind: 'commit', ref: '533ce86', note: 'escopo do gate ao workspace (causa raiz do fan-out)' },
      { kind: 'record', ref: 'docs/registros', note: 'independência dos gates + Coding Harness V3 command-execution-policy' },
    ],
  },
  {
    id: 'agency.isolated-workspace',
    name: 'Workspace isolado (worktree)',
    description: 'Trabalhar numa git worktree isolada, resiliente a falhas transitórias de filesystem.',
    domain: 'agency',
    maturity: 'operational',
    dependsOn: [],
    meaning: 'Cada tentativa de mudança acontece isolada, sem tocar a árvore principal — contenção é pré-requisito de segurança.',
    advancement: 'Operacional; footgun conhecido no dispose de junction node_modules é tratado.',
    proofRefs: [
      { kind: 'commit', ref: '8dc2228', note: 'worktree resiliente a falha transitória de FS' },
      { kind: 'record', ref: 'docs/registros', note: 'ADR-001 worktree executor' },
    ],
  },
  {
    id: 'agency.produce-change',
    name: 'Produzir alteração de código',
    description: 'Um coder backend (Ollama/OpenAI) produz uma mudança de código coerente.',
    domain: 'agency',
    maturity: 'proven',
    dependsOn: ['agency.edit-file', 'agency.run-tests', 'compute.selection'],
    meaning: 'O núcleo da agência: transformar uma intenção aprovada em código real, por um executor substituível.',
    advancement: 'Barreira local de RAM (qwen3-coder 30B derrama) e capacidade do agente pago; operacional exige reprodutibilidade.',
    proofRefs: [
      { kind: 'commit', ref: '87a3ad8', note: 'PIN-02 provado ao vivo pelo self-dev' },
      { kind: 'commit', ref: 'fbf0baa', note: 'fallback governado de coder por capacidade' },
    ],
  },
  {
    id: 'agency.verify-change',
    name: 'Verificar alteração',
    description: 'Conferir a mudança contra o contrato aprovado (gates + parecer do Verifier).',
    domain: 'agency',
    maturity: 'proven',
    dependsOn: ['agency.run-tests', 'governance.verifier'],
    meaning: 'Verificar é separado de produzir: o Anima confere a própria obra contra o que foi aprovado antes de pedir revisão.',
    advancement:
      'Falso positivo já observado (Verifier "verified" para mudança trivial); operacional exige verificação que não engane a revisão humana.',
    proofRefs: [
      { kind: 'commit', ref: '824c714', note: 'requisitos de prova heterogêneos pós-review' },
      { kind: 'record', ref: 'docs/registros', note: 'seq4→seq5: verified foi falso positivo, corrigido por request_changes' },
    ],
  },
  {
    id: 'agency.recovery-correction',
    name: 'Recovery e correção',
    description: 'Replanejar após falha, corrigir após request_changes e retomar sob autoridade humana.',
    domain: 'agency',
    maturity: 'proven',
    dependsOn: ['agency.produce-change', 'governance.recovery-authority', 'governance.attempt'],
    meaning: 'Falhar não é o fim: o Anima produz o sucessor correto, preserva o que já valia e retoma com +1 tentativa autorizada.',
    advancement: 'Reproduzir correções bem-sucedidas de forma rotineira até virar operacional.',
    proofRefs: [
      { kind: 'commit', ref: '4b5c500', note: 'replanejamento após falha determinística' },
      { kind: 'commit', ref: '1c6c656', note: 'Human Recovery Authority' },
    ],
  },
  {
    id: 'agency.supervised-self-development',
    name: 'Self-development supervisionado',
    description: 'Cadeia completa backlog → attempt → worktree → coder → gates → review → aceite humano.',
    domain: 'agency',
    maturity: 'proven',
    dependsOn: ['agency.produce-change', 'agency.verify-change', 'governance.review', 'interaction.resident-host'],
    meaning: 'O Anima constrói o próprio Anima sob supervisão: uma solicitação aprovada percorre toda a esteira até revisão humana.',
    advancement:
      'Operacional exige reprodutibilidade local (RAM) e provas pagas confiáveis; hoje é comprovado ponta a ponta, não rotineiro.',
    proofRefs: [
      { kind: 'work_item', ref: '8a2515d8', note: 'work item que foi fim-a-fim até review→completed com OpenAI forte (2026-09-11)' },
      { kind: 'milestone', ref: 'docs/marcos/008-dev-local-v1-review-rework-incremental.md' },
    ],
  },
  {
    id: 'agency.detect-deficiency',
    name: 'Detectar deficiência própria',
    description: 'O Anima percebe sozinho uma limitação/lacuna na própria capacidade.',
    domain: 'agency',
    maturity: 'projected',
    dependsOn: ['agency.supervised-self-development', 'governance.verifier', 'memory.event-history'],
    target: { description: 'Primeiro degrau rumo ao self-development contínuo.' },
    meaning: 'Em vez de esperar um humano apontar o que falta, o Anima infere as próprias deficiências a partir de attempts, verifier e histórico.',
    advancement: 'Falta o motor que lê event log + attempts + verifier e formula uma deficiência acionável.',
  },
  {
    id: 'agency.formulate-improvement',
    name: 'Formular melhoria própria',
    description: 'Transformar uma deficiência detectada numa proposta de melhoria concreta.',
    domain: 'agency',
    maturity: 'projected',
    dependsOn: ['agency.detect-deficiency'],
    target: { description: 'Segundo degrau rumo ao self-development contínuo.' },
    meaning: 'O Anima propõe a própria evolução: dada uma deficiência, formula o que mudar e por quê.',
    advancement: 'Depende de detectar deficiência própria de forma confiável.',
  },
  {
    id: 'agency.validate-improvement',
    name: 'Validar melhoria própria',
    description: 'Provar que uma melhoria auto-formulada de fato melhora, sem regressão.',
    domain: 'agency',
    maturity: 'projected',
    dependsOn: ['agency.formulate-improvement', 'agency.verify-change'],
    target: { description: 'Terceiro degrau rumo ao self-development contínuo.' },
    meaning: 'Antes de incorporar, o Anima valida a própria melhoria com evidência — auto-modificação sob prova.',
    advancement: 'Depende de formular melhoria e de verificação forte o suficiente para autojulgamento.',
  },
  {
    id: 'agency.continuous-self-development',
    name: 'Self-development contínuo',
    description: 'O Anima detecta, formula, valida e incorpora melhorias próprias dentro da authority, sem loop humano constante.',
    domain: 'agency',
    maturity: 'projected',
    dependsOn: ['agency.validate-improvement', 'agency.recovery-correction', 'governance.progressive-autonomy'],
    target: {
      description: 'Norte do arco de agência: evolução própria contínua e segura sob mandato.',
      milestone: 'docs/marcos/005-autonomia-progressiva-e-identidade-una.md',
    },
    meaning: 'A capacidade mais ambiciosa do arco: o Anima evolui a si mesmo continuamente, dentro de limites explícitos e revogáveis.',
    advancement: 'Falta toda a cadeia detectar → formular → validar → incorporar operando sob autonomia progressiva comprovada.',
  },

  // ─── GOVERNANÇA ─────────────────────────────────────────────────────────────
  {
    id: 'governance.authority',
    name: 'Authority (mandato)',
    description: 'Derivar um envelope de trabalho a partir de intenção e limites e impedir o que estiver fora dele.',
    domain: 'governance',
    maturity: 'proven',
    dependsOn: ['memory.persistence'],
    meaning: 'A aprovação evolui de micropermissão para mandato: o usuário aprova intenção e limites; o sistema barra o resto (fail-closed).',
    advancement: 'Autoridades pagas por-item são efêmeras (expiram); operacional pleno exige envelopes reutilizáveis e revogáveis por evidência.',
    proofRefs: [
      { kind: 'milestone', ref: 'docs/marcos/005-autonomia-progressiva-e-identidade-una.md' },
      { kind: 'route', ref: 'apps/web/app/api/work-orchestration/paid-compute-authorizations' },
    ],
  },
  {
    id: 'governance.attempt',
    name: 'Attempt e lineage',
    description: 'Tentativas persistentes com claim exclusivo e rastreio de sucessores (decomposição, replan, correção) preservando a história.',
    domain: 'governance',
    maturity: 'operational',
    dependsOn: ['memory.persistence'],
    meaning: 'Cada esforço é uma attempt durável e exclusiva com linhagem: a unidade que o sistema retoma de checkpoints, replaneja e audita, sem apagar história.',
    advancement: 'Operacional; recuperação de attempt "dead-end" (start manual sem attempt) é ação humana via RPC; cadeias de sucessão longas ainda não são rotina.',
    proofRefs: [
      { kind: 'milestone', ref: 'docs/marcos/003-trabalho-autonomo-seguro.md' },
      { kind: 'commit', ref: '4b5c500', note: 'replanejamento (sucessor proposed)' },
      { kind: 'commit', ref: 'e090013', note: 'decomposição com retomada de checkpoint' },
    ],
  },
  {
    id: 'governance.review',
    name: 'Review',
    description: 'Parar antes do efeito externo e pedir revisão humana (review request fail-closed).',
    domain: 'governance',
    maturity: 'operational',
    dependsOn: ['governance.attempt'],
    meaning: 'Nenhuma mudança de impacto vaza sem revisão: o sistema para ANTES do PR e espera a decisão humana.',
    advancement: 'Já operacional; evolução é promover classes de efeito a autônomas por evidência (autonomia progressiva).',
    proofRefs: [
      { kind: 'route', ref: 'apps/web/app/api/work-orchestration/review-requests' },
      { kind: 'milestone', ref: 'docs/marcos/008-dev-local-v1-review-rework-incremental.md' },
    ],
  },
  {
    id: 'governance.verifier',
    name: 'Verifier',
    description: 'Parecer append-only, puro e advisory que confere o resultado contra o contrato aprovado.',
    domain: 'governance',
    maturity: 'proven',
    dependsOn: ['agency.run-tests'],
    meaning: 'Um segundo par de olhos automatizado: opina se o resultado cumpre o contrato, sem aceitar/publicar por conta própria.',
    advancement: 'Falso positivo já observado; operacional exige que "verified" resista à revisão humana de forma consistente.',
    proofRefs: [
      { kind: 'commit', ref: '824c714', note: 'Verifier v2 — cobertura heterogênea' },
      { kind: 'record', ref: 'docs/registros', note: 'VerifierOpinionV1 append-only, fail-open' },
    ],
  },
  {
    id: 'governance.budgets',
    name: 'Budgets e limites',
    description: 'Orçamento local e externo com bloqueio temporal, re-admissão e fail-closed.',
    domain: 'governance',
    maturity: 'operational',
    dependsOn: ['governance.authority'],
    meaning: 'O Anima trabalha dentro de um envelope econômico: quando o orçamento esgota, ele bloqueia e re-admite sem perder trabalho.',
    advancement: 'Já operacional; settlement de custo real de compute pago ainda é barreira (ver compute.paid-settlement).',
    proofRefs: [
      { kind: 'commit', ref: '6bef210', note: 'orçamento V0 — bloqueio temporal + re-admissão' },
      { kind: 'commit', ref: '636aa7b', note: 'interrupção de orçamento retoma do checkpoint' },
    ],
  },
  {
    id: 'governance.recovery-authority',
    name: 'Human Recovery Authority',
    description: 'Autorizar +1 tentativa após saldo esgotado, append-only e anti-loop.',
    domain: 'governance',
    maturity: 'proven',
    dependsOn: ['governance.budgets', 'governance.attempt'],
    meaning: 'Quando o envelope trava, o humano — e só o humano — pode conceder mais uma tentativa, sem reabrir loops infinitos.',
    advancement: 'Reproduzir concessões de recovery de forma rotineira mantendo a barreira anti-loop.',
    proofRefs: [{ kind: 'commit', ref: '1c6c656', note: 'authorize_work_resume' }],
  },
  {
    id: 'governance.progressive-autonomy',
    name: 'Autonomia progressiva',
    description: 'Capacidades conquistam autoridade por evidência de segurança e a perdem por evidência de risco.',
    domain: 'governance',
    maturity: 'specified',
    dependsOn: ['governance.authority', 'governance.verifier', 'memory.event-history'],
    target: {
      description: 'Motor que promove/rebaixa autoridade por evidência — sem teto filosófico, alterar a própria política é o ato mais protegido.',
      milestone: 'docs/marcos/006-politica-de-seguranca-como-maturidade-maxima.md',
    },
    meaning: 'O princípio central da maturidade do Anima está ESPECIFICADO (Marcos 005/006), mas o motor genérico que move autoridade por evidência ainda não existe.',
    advancement: 'Falta o mecanismo que lê evidência e ajusta authority automaticamente, com processo reforçado para a política máxima.',
    proofRefs: [{ kind: 'milestone', ref: 'docs/marcos/005-autonomia-progressiva-e-identidade-una.md' }],
  },

  // ─── COMPUTE ────────────────────────────────────────────────────────────────
  {
    id: 'compute.local-execution',
    name: 'Execução local',
    description: 'Rodar modelos e o host residente localmente (Ollama, resident host in-process).',
    domain: 'compute',
    maturity: 'operational',
    dependsOn: [],
    meaning: 'local-first: o Anima prefere capacidade local e mantém um host residente que acorda por Realtime para trabalhar.',
    advancement: 'Barreira de RAM (16GB) limita modelos grandes; 32GB ou burst on-demand contorna.',
    proofRefs: [
      { kind: 'record', ref: 'docs/registros', note: 'Resident Local Host V0 (npm run local-host)' },
      { kind: 'commit', ref: '1d4a79f', note: 'caracterização de capacidade da Goma' },
    ],
  },
  {
    id: 'compute.external-provider',
    name: 'Provider externo',
    description: 'Chamar providers externos (OpenAI) por uma borda única governada (admit antes do fetch).',
    domain: 'compute',
    // Auditoria 2026-09-16: rebaixada operational→proven. As chamadas pagas são
    // deliberadamente raras e gated (autoridade efêmera por item), então não há
    // "uso rotineiro reproduzido" que justifique operational — só provas concretas.
    maturity: 'proven',
    dependsOn: ['governance.authority'],
    meaning: 'local-first != local-only: o Anima usa modelos externos enquanto forem mais capazes, sempre por uma borda única que admite antes de gastar.',
    advancement: 'Transporte comprovado; operacional exigiria uso reproduzido, hoje limitado por autoridades pagas efêmeras e pela barreira de settlement de custo real.',
    proofRefs: [
      { kind: 'commit', ref: '78dfc3f', note: 'governança OpenAI global (borda única)' },
      { kind: 'commit', ref: '43b47c2', note: 'coder pago OpenAI governado até review' },
    ],
  },
  {
    id: 'compute.selection',
    name: 'Seleção de compute',
    description: 'Rotear entre Ollama × OpenAI (e casar recursos de cloud) por política e economia.',
    domain: 'compute',
    maturity: 'proven',
    dependsOn: ['compute.local-execution', 'compute.external-provider', 'memory.event-history'],
    meaning: 'A escolha do provider é decisão de capacidade e política — nunca parte da identidade. O Router decide; OFF é invisível.',
    advancement: 'Reproduzir seleção sob cargas reais variadas; matching de recurso de cloud ainda é WIP.',
    proofRefs: [
      { kind: 'commit', ref: '38494d5', note: 'Compute Router V1 (feature gate)' },
      { kind: 'commit', ref: '9fa181c', note: 'ponte economic observations → Router' },
    ],
  },
  {
    id: 'compute.provisioning',
    name: 'Provisionamento on-demand',
    description: 'Ciclo de vida governado de nós de compute sob demanda (lease + reconciler + teto de custo).',
    domain: 'compute',
    maturity: 'proven',
    dependsOn: ['compute.selection', 'governance.budgets'],
    meaning: '"necessidade ≠ gasto": o Anima provisiona compute só dentro de um envelope de segurança com custo máximo obrigatório.',
    advancement: 'Comprovado com recurso OWNED; operacional exige o ciclo pago completo com settlement.',
    proofRefs: [
      { kind: 'record', ref: 'docs/registros', note: 'Provisionamento On-Demand V1' },
      { kind: 'doc', ref: 'docs/arquitetura/provisionamento-lease-seguranca.md' },
    ],
  },
  {
    id: 'compute.cloud-self-hosted',
    name: 'Cloud self-hosted + resiliência de sessão',
    description: 'Subir e usar um nó de inferência próprio na nuvem (RunPod cold-start + túnel) e reprovisionar/teardown de forma governada.',
    domain: 'compute',
    maturity: 'implemented',
    dependsOn: ['compute.provisioning'],
    meaning:
      'Quando o local não basta, o Anima levanta o próprio nó de GPU na nuvem — sem depender de endpoint de terceiros — e sabe trocar de máquina ruim sem estourar o envelope.',
    advancement:
      'Barreira viva: RUNPOD_AUTOPROVISION_END_TO_END=FAIL (pod RUNNING mas endpoint não publica); falta adapter de sessão resiliente vivo e migração de settlement aplicada.',
    proofRefs: [
      { kind: 'commit', ref: '37cf35f', note: 'endurece provisionador RunPod para cold-start' },
      { kind: 'record', ref: 'docs/registros', note: 'RunPod readiness em camadas + Resilient Cloud Session V1 (WIP)' },
    ],
  },
  {
    id: 'compute.paid-settlement',
    name: 'Settlement de custo pago',
    description: 'Liquidar o custo REAL de compute pago (actual-cost) no ledger, append-only.',
    domain: 'compute',
    maturity: 'implemented',
    dependsOn: ['compute.external-provider', 'governance.budgets'],
    meaning: 'Reservar não é gastar e derivar não é liquidar: o Anima precisa fechar o custo real do que consumiu, com honestidade.',
    advancement:
      'Seam pronto (ProviderPricingV1, calculateApiAttemptCost) e infra mínima canonizada, mas pricing=null p/ gpt-5.6-terra ⇒ custo real indisponível; migração de settlement não aplicada.',
    proofRefs: [
      { kind: 'commit', ref: 'b14a32c', note: 'infraestrutura mínima de settlement do ledger de compute pago' },
      { kind: 'record', ref: 'docs/registros', note: 'benchmark settlement V3 — barreira de actual-cost' },
    ],
  },

  // ─── INTERAÇÃO ──────────────────────────────────────────────────────────────
  {
    id: 'interaction.chat',
    name: 'Chat',
    description: 'A entrada conversacional unificada do Anima.',
    domain: 'interaction',
    maturity: 'operational',
    dependsOn: ['memory.persistence'],
    meaning: 'O chat é a única frente conversacional do produto; telas auxiliares só visualizam e confirmam.',
    advancement: 'Operacional; evolui com proatividade cognitiva (o Anima puxando assunto sobre o futuro).',
    proofRefs: [{ kind: 'route', ref: 'apps/web/app/(app)/chat' }],
  },
  {
    id: 'interaction.web-interface',
    name: 'Interface web',
    description: 'As telas do app (home, grafo, entidades, histórico, evolução) sobre a mesma base de dados.',
    domain: 'interaction',
    maturity: 'operational',
    dependsOn: ['memory.persistence'],
    meaning: 'A camada visual que projeta o estado do Anima — inclui esta própria tela de evolução.',
    advancement: 'Operacional; esta tela /evolution é o V0 da projeção do autoconhecimento do sistema.',
    proofRefs: [{ kind: 'route', ref: 'apps/web/app/(app)', note: 'grupo de rotas do app' }],
  },
  {
    id: 'interaction.resident-host',
    name: 'Resident Host',
    description: 'Runtime residente in-process que acorda por Realtime e executa trabalho admitido.',
    domain: 'interaction',
    maturity: 'operational',
    dependsOn: ['interaction.web-interface', 'governance.attempt'],
    meaning: 'O Anima tem um "corpo" residente que roda continuamente e reage a eventos, em vez de só responder a cliques.',
    advancement: 'Operacional (idle → item → verified → review provado ao vivo); evolui com perfis autônomos vivos.',
    proofRefs: [
      { kind: 'record', ref: 'docs/registros', note: 'Marco Resident Local Host V0' },
      { kind: 'commit', ref: '3d5aa65', note: 'autoridade de execução do Resident Host' },
    ],
  },
  {
    id: 'interaction.action-cards',
    name: 'Interação com ações',
    description: 'Confirmar, aprovar, aceitar, pedir mudanças e retomar trabalho pelo chat e pela CLI.',
    domain: 'interaction',
    maturity: 'operational',
    dependsOn: ['interaction.chat', 'governance.review'],
    meaning: 'As decisões humanas de impacto acontecem na própria conversa (cards) e na CLI oficial — mesma camada de serviços.',
    advancement: 'Operacional; web e CLI compartilham os serviços com identidade residente (RLS, sem service_role).',
    proofRefs: [
      { kind: 'commit', ref: 'de14178', note: 'CLI operacional como adapter oficial' },
      { kind: 'test', ref: 'apps/web/app/(app)/chat/_components/WorkProposalCard.test.tsx' },
    ],
  },
  {
    id: 'interaction.local-executor-arm',
    name: 'Braço executor local (GUI/OS)',
    description: 'Perceber e operar aplicações/OS locais como braço executor provider-neutral sob mandato.',
    domain: 'interaction',
    maturity: 'specified',
    dependsOn: ['interaction.resident-host', 'governance.authority'],
    target: {
      description: 'Operar interfaces locais (abrir, navegar, clicar, digitar) sob mandato, com cada classe de efeito amadurecendo à parte.',
      milestone: 'docs/marcos/007-interacao-com-computador-e-aplicacoes-locais.md',
    },
    meaning: 'O Anima estende os nós locais à camada GUI: enxergar a tela e operar apps, sempre sob escopo/impacto/duração aprovados.',
    advancement: 'Estado estreito: só prova inicial do canal; falta taxonomia, contrato e implementação por classe de efeito.',
    proofRefs: [{ kind: 'milestone', ref: 'docs/marcos/007-interacao-com-computador-e-aplicacoes-locais.md' }],
  },
  {
    id: 'interaction.cognitive-proactivity',
    name: 'Proatividade cognitiva',
    description: 'O Anima observa, relaciona no tempo, projeta cenários e puxa conversa sobre o futuro.',
    domain: 'interaction',
    maturity: 'projected',
    dependsOn: ['interaction.chat', 'memory.narrative-memory', 'understanding.world-model'],
    target: {
      description: 'Passar de "receber → armazenar → exibir" para "observar → lembrar → relacionar → refletir → projetar → conversar" (capacidade Prisma).',
    },
    meaning: 'A proatividade é COGNITIVA, não operacional: o Anima nota mudanças e conversa sobre o futuro — sem iniciar execuções sozinho.',
    advancement: 'Depende da memória narrativa e do world model existirem para relacionar dados no tempo.',
  },
];

/** Constrói o grafo de capacidades do Anima a partir do registro V0. */
export function getAnimaCapabilityGraph(): CapabilityGraph {
  return buildCapabilityGraph(ANIMA_CAPABILITY_REGISTRY_V0);
}
