import type {CommandResult} from './worktree';
import {GitBranchPublicationProvider,BranchPublicationFailure} from './git-branch-publication';
import type {ProtectedIntegrationRequest} from '@anima/core';
const BASE='a'.repeat(40),COMMIT='b'.repeat(40);
const request:ProtectedIntegrationRequest={protocolVersion:1,idempotencyKey:'integration-publication:auth:commit',authorizationDecisionId:'auth',acceptedResultEventId:'result',correlation:{workItemId:'work',attemptId:'attempt',approvedProposalVersion:1},target:{providerId:'git-branch-publication-v1',repositoryId:'https://github.com/geanpfefer/anima',remoteName:'origin',baseBranch:'main'},baseSha:BASE,localBranch:'anima-work/attempt',remoteBranch:'anima-work/attempt',commitSha:COMMIT};
const result=(stdout='',exitCode=0):CommandResult=>({command:'git',exitCode,stdout,stderr:'',durationMs:1,timedOut:false,cancelled:false});
const runner=(remoteBefore:string|null,remoteAfter:string|null=remoteBefore,pushExit=0)=>{let inspections=0;const calls:string[][]=[];const run=jest.fn(async(args:readonly string[])=>{calls.push([...args]);const command=args.join(' ');if(command.startsWith('remote get-url'))return result('https://github.com/GeanPfefer/anima.git\n');if(command.startsWith('rev-parse'))return result(`${COMMIT}\n`);if(command.startsWith('cat-file')||command.startsWith('merge-base'))return result();if(command.includes('refs/heads/main'))return result(`${BASE}\trefs/heads/main\n`);if(command.startsWith('ls-remote')){const sha=inspections++===0?remoteBefore:remoteAfter;return result(sha?`${sha}\trefs/heads/anima-work/attempt\n`:'');}if(command.startsWith('push'))return result('',pushExit);return result('',1);});return{run,calls};};
describe('GitBranchPublicationProvider',()=>{
 test('branch inexistente usa refspec explícito e verifica após push',async()=>{const fake=runner(null,COMMIT);const receipt=await new GitBranchPublicationProvider('repo',fake.run).publishBranch(request);expect(receipt.disposition).toBe('created');expect(fake.calls.find(call=>call[0]==='push')).toEqual(['push','--no-follow-tags','origin','refs/heads/anima-work/attempt:refs/heads/anima-work/attempt']);});
 test('o push nunca carrega force, wildcard ou tags — nem sob push.followTags',async()=>{const fake=runner(null,COMMIT);await new GitBranchPublicationProvider('repo',fake.run).publishBranch(request);const push=fake.calls.find(call=>call[0]==='push')!;expect(push).toContain('--no-follow-tags');expect(push).not.toContain('--tags');expect(push).not.toContain('--follow-tags');expect(push.some(arg=>arg.startsWith('+')||arg.includes('*')||arg==='--force'||arg==='-f')).toBe(false);const refspec=push.at(-1)!;expect(refspec).toBe('refs/heads/anima-work/attempt:refs/heads/anima-work/attempt');});
 test('branch existente no SHA correto reconcilia sem push',async()=>{const fake=runner(COMMIT);const receipt=await new GitBranchPublicationProvider('repo',fake.run).publishBranch(request);expect(receipt.disposition).toBe('already_existed');expect(fake.calls.some(call=>call[0]==='push')).toBe(false);});
 test('branch existente divergente falha fechado',async()=>{const fake=runner('c'.repeat(40));await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch(request)).rejects.toMatchObject({code:'remote_branch_conflict'});});
 test('branch local inexistente falha antes de push',async()=>{const fake=runner(null);fake.run.mockImplementationOnce(async()=>result('https://github.com/GeanPfefer/anima.git\n')).mockImplementationOnce(async()=>result('',1));await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch(request)).rejects.toMatchObject({code:'local_branch_missing'});expect(fake.calls.some(call=>call[0]==='push')).toBe(false);});
 test('branch local em commit divergente falha',async()=>{const fake=runner(null);fake.run.mockImplementationOnce(async()=>result('https://github.com/GeanPfefer/anima.git\n')).mockImplementationOnce(async()=>result(`${'c'.repeat(40)}\n`));await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch(request)).rejects.toMatchObject({code:'local_commit_mismatch'});});
 test('repository e base divergentes falham fechado',async()=>{const repo=runner(null);repo.run.mockImplementationOnce(async()=>result('https://example.invalid/outro.git\n'));await expect(new GitBranchPublicationProvider('repo',repo.run).publishBranch(request)).rejects.toMatchObject({code:'repository_mismatch'});const base=runner(null);base.run.mockImplementationOnce(async()=>result('https://github.com/GeanPfefer/anima.git\n')).mockImplementationOnce(async()=>result(`${COMMIT}\n`)).mockImplementationOnce(async()=>result()).mockImplementationOnce(async()=>result()).mockImplementationOnce(async()=>result(`${'c'.repeat(40)}\trefs/heads/main\n`));await expect(new GitBranchPublicationProvider('repo',base.run).publishBranch(request)).rejects.toMatchObject({code:'base_mismatch'});});
 test('erro de push com remote correto reconcilia pelo fato',async()=>{const fake=runner(null,COMMIT,1);await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch(request)).resolves.toMatchObject({commitSha:COMMIT});});
 test('erro de push sem prova remota não produz receipt',async()=>{const fake=runner(null,null,1);await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch(request)).rejects.toMatchObject({code:'push_unverified'});});
 test('request de branch arbitrária é recusada',async()=>{const fake=runner(null);await expect(new GitBranchPublicationProvider('repo',fake.run).publishBranch({...request,remoteBranch:'main'})).rejects.toBeInstanceOf(BranchPublicationFailure);expect(fake.run).not.toHaveBeenCalled();});
});
