import type{BranchPublicationReceipt,ReviewRequestReceipt,ReviewRequestProvider,ProtectedIntegrationRequest}from'@anima/core';import{branchPublicationKey,reviewRequestKey}from'@anima/core';import{createAndPersistReviewRequest}from'./review-request-operation';

const request:ProtectedIntegrationRequest={protocolVersion:1,idempotencyKey:'k',authorizationDecisionId:'auth',acceptedResultEventId:'result',correlation:{workItemId:'work',attemptId:'attempt',approvedProposalVersion:1},target:{providerId:'provider',repositoryId:'repo',remoteName:'origin',baseBranch:'main'},baseSha:'a'.repeat(40),localBranch:'anima-work/attempt',remoteBranch:'anima-work/attempt',commitSha:'b'.repeat(40)};
const branch:BranchPublicationReceipt={kind:'branch_publication',receiptId:'branch-receipt',idempotencyKey:branchPublicationKey(request),providerId:'provider',repositoryId:'repo',remoteName:'origin',remoteBranch:'anima-work/attempt',commitSha:'b'.repeat(40),baseBranch:'main',verifiedBaseSha:'a'.repeat(40),disposition:'created'};
const review:ReviewRequestReceipt={kind:'review_request',receiptId:'review-receipt',idempotencyKey:reviewRequestKey(request),providerId:'provider',repositoryId:'repo',remoteName:'origin',reviewId:'42',reviewReference:'https://example.invalid/pull/42',state:'open',sourceBranch:'anima-work/attempt',sourceCommitSha:'b'.repeat(40),baseBranch:'main',verifiedBaseSha:'a'.repeat(40),disposition:'created'};
const provider=(over:Partial<ReviewRequestProvider>={}):ReviewRequestProvider=>({id:'provider',inspectBranch:jest.fn(),publishBranch:jest.fn(),inspectReviewRequest:jest.fn().mockResolvedValue(null),createReviewRequest:jest.fn().mockResolvedValue(review),...over});

test('cria o PR só quando não existe, aplica a máquina de estados e persiste; replay idempotente',async()=>{const p=provider();const persist=jest.fn().mockResolvedValueOnce({action:'recorded',eventSeq:1}).mockResolvedValueOnce({action:'replayed',eventSeq:1});const first=await createAndPersistReviewRequest(request,branch,p,persist);const retry=await createAndPersistReviewRequest(request,branch,p,persist);expect(first.state.status).toBe('review_request_created');expect(retry.persistence.action).toBe('replayed');expect(p.createReviewRequest).toHaveBeenCalledTimes(2);expect(persist).toHaveBeenCalledTimes(2);});
test('PR já existente (inspect) reconcilia sem criar de novo',async()=>{const p=provider({inspectReviewRequest:jest.fn().mockResolvedValue(review),createReviewRequest:jest.fn()});const persist=jest.fn().mockResolvedValue({action:'recorded',eventSeq:1});const out=await createAndPersistReviewRequest(request,branch,p,persist);expect(out.state.status).toBe('review_request_created');expect(p.createReviewRequest).not.toHaveBeenCalled();expect(persist).toHaveBeenCalledTimes(1);});
test('receipt de review inconsistente nunca chega à persistência',async()=>{const p=provider({createReviewRequest:jest.fn().mockResolvedValue({...review,sourceCommitSha:'c'.repeat(40)})});const persist=jest.fn();await expect(createAndPersistReviewRequest(request,branch,p,persist)).rejects.toThrow(/review_request_created|corresponde|receipt/i);expect(persist).not.toHaveBeenCalled();});
test('branch receipt inconsistente falha antes de criar o PR',async()=>{const p=provider();const persist=jest.fn();await expect(createAndPersistReviewRequest(request,{...branch,commitSha:'c'.repeat(40)},p,persist)).rejects.toThrow();expect(persist).not.toHaveBeenCalled();});
test('provider divergente da request não inspeciona, cria nem persiste',async()=>{const p=provider({id:'outro-provider'});const persist=jest.fn();await expect(createAndPersistReviewRequest(request,branch,p,persist)).rejects.toThrow(/[Pp]rovider/);expect(p.inspectReviewRequest).not.toHaveBeenCalled();expect(p.createReviewRequest).not.toHaveBeenCalled();expect(persist).not.toHaveBeenCalled();});
test('falha de persistência após efeito permite retry posterior',async()=>{const p=provider({inspectReviewRequest:jest.fn().mockResolvedValueOnce(null).mockResolvedValueOnce(review),createReviewRequest:jest.fn().mockResolvedValueOnce(review)});const persist=jest.fn().mockRejectedValueOnce(new Error('db unavailable')).mockResolvedValueOnce({action:'recorded',eventSeq:2});await expect(createAndPersistReviewRequest(request,branch,p,persist)).rejects.toThrow('db unavailable');await expect(createAndPersistReviewRequest(request,branch,p,persist)).resolves.toMatchObject({persistence:{action:'recorded'}});});
